##spring:
##  profiles: default
security:
  oauth2:
    client:
      clientId: ${clientId}
      clientSecret: ${clientSecret}
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user

#      dev
#      clientId: 92593a847004026d65ff
#      clientSecret: c9e1750c7b134309d10ebaca28a05fa7bb2f50c7

---
spring:
  profiles: cloud
security:
  oauth2:
    client:
      clientId: ${clientId}
      clientSecret: ${clientSecret}
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl: true